package po;
// Generated 2017-6-22 15:00:49 by Hibernate Tools 4.3.1



/**
 * Datum generated by hbm2java
 */
public class Datum  implements java.io.Serializable {


     private Integer id;
     private String num;
     private String name;
     private String sex;
     private Integer age;
     private Float score;

    public Datum() {
    }

    public Datum(String num, String name, String sex, Integer age, Float score) {
       this.num = num;
       this.name = name;
       this.sex = sex;
       this.age = age;
       this.score = score;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNum() {
        return this.num;
    }
    
    public void setNum(String num) {
        this.num = num;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }




}


