package po;
// Generated 2017-6-22 15:00:49 by Hibernate Tools 4.3.1



/**
 * PublicSkill generated by hbm2java
 */
public class PublicSkill  implements java.io.Serializable {


     private Integer id;
     private String skillName;
     private String introduce;

    public PublicSkill() {
    }

	
    public PublicSkill(String skillName) {
        this.skillName = skillName;
    }
    public PublicSkill(String skillName, String introduce) {
       this.skillName = skillName;
       this.introduce = introduce;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }
    public String getIntroduce() {
        return this.introduce;
    }
    
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }




}


