package po;
// Generated 2017-6-22 15:00:49 by Hibernate Tools 4.3.1



/**
 * PublicEquip generated by hbm2java
 */
public class PublicEquip  implements java.io.Serializable {


     private Integer id;
     private String equipName;
     private String introduce;

    public PublicEquip() {
    }

	
    public PublicEquip(String equipName) {
        this.equipName = equipName;
    }
    public PublicEquip(String equipName, String introduce) {
       this.equipName = equipName;
       this.introduce = introduce;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEquipName() {
        return this.equipName;
    }
    
    public void setEquipName(String equipName) {
        this.equipName = equipName;
    }
    public String getIntroduce() {
        return this.introduce;
    }
    
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }




}


