package po;
// Generated 2017-6-4 21:32:42 by Hibernate Tools 4.3.1



/**
 * Weather generated by hbm2java
 */
public class Weather  implements java.io.Serializable {


     private Integer id;
     private String city;
     private String situation;

    public Weather() {
    }

    public Weather(String city, String situation) {
       this.city = city;
       this.situation = situation;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getSituation() {
        return this.situation;
    }
    
    public void setSituation(String situation) {
        this.situation = situation;
    }




}


